# Generated by Django 3.0.7 on 2021-12-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='author',
        ),
    ]
