# Generated by Django 3.0.7 on 2021-12-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211209_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='name',
        ),
    ]
