# Generated by Django 3.0.7 on 2021-12-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211213_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
